<a href="https://colab.research.google.com/github/DEVENDRAKUMAWAT650/Python_in_AWS-ML/blob/main/Day11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy** **array** **operation**

In [6]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr[2])
print(arr[0:4]) #slicing
print(arr[0:5:2]) #slicing with step
print(arr[:])
print(arr[-1])
print(arr[::-1])
print(arr[3:5])

3
[1 2 3 4]
[1 3 5]
[1 2 3 4 5 6]
6
[6 5 4 3 2 1]
[4 5]


In [12]:
#2D
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print(arr1[0:2])# row colum
print(arr1[0:2,0:3])
print(arr1[0,0])
print(arr1[0,:])


[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3]
 [5 6 7]]
1
[1 2 3 4]


In [26]:
arr2 =  np.array([[10,20],[30,40],[50,60]])
print(arr2)
print(arr2[1,1])
print(arr2[0,0])
#print(arr2[1:,1:1 ])
print(arr2[:,1])
print(arr2[[0,1],[1,0]])
print(arr2[[0,1],[0,1]])
print(arr2[[0,1,2],[1,1,0]])

[[10 20]
 [30 40]
 [50 60]]
40
10
[20 40 60]
[20 30]
[10 40]
[20 40 50]


In [42]:
import numpy as np

country = np.array([
    [2453, 75, 183975],
    [5795, 99, 573705],
    [4100, 36, 147600],
    [7526, 86, 647236],
    [9528, 45, 428760],
    [10788, 17, 183396]
])

print(country)
print(country[[0,1],[2,1]])
print(country[[0,0,4,5],[0,1,2,2]])
print(country[[2,3,3,3],[0,0,1,2]])
#print(country[[2,3],[0,0:3]])
print(country[[4,5],[1,1]])

[[  2453     75 183975]
 [  5795     99 573705]
 [  4100     36 147600]
 [  7526     86 647236]
 [  9528     45 428760]
 [ 10788     17 183396]]
[183975     99]
[  2453     75 428760 183396]
[  4100   7526     86 647236]
[45 17]


In [51]:
#3d
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)
print(arr3[0,1,2])
print('=>',arr3[0])
print('=>>',arr3[0,0])
print('=>>>',arr3[0,0,0])
print(arr3[:,0])
print("All Block -> all rows -> cols 0",arr3[:,:,0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6
=> [[1 2 3]
 [4 5 6]]
=>> [1 2 3]
=>>> 1
[[1 2 3]
 [7 8 9]]
All Block -> all rows -> cols 0 [[ 1  4]
 [ 7 10]]


In [52]:
# for loop on numpy
#1d
arr = np.array([1,2,3,4,5,6])
for x in arr:
  print(x)

1
2
3
4
5
6


In [61]:
#2d
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
for x in arr1:
  for y in x:
    print(y)


[[1 2 3 4]
 [5 6 7 8]]
1
2
3
4
5
6
7
8


In [62]:
#3d
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)
for block in arr3:
    for row in block:
        for x in row:
            print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
2
3
4
5
6
7
8
9
10
11
12


In [64]:
for x in np.nditer(arr3):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [66]:
for i in arr3.ravel():
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


**Shorting**

In [69]:
arr = np.array([10,20,3,40,50,6])
print(arr)
print(np.sort(arr)) # ascendign
print(np.sort(arr)[::-1]) # decending

[10 20  3 40 50  6]
[ 3  6 10 20 40 50]
[50 40 20 10  6  3]


In [74]:
#2d
arr1 = np.array([[10,3,40],[20,6,100]])
print(arr1)
print(np.sort(arr1))
print(np.sort(arr1,axis=0))
print(np.sort(arr1,axis=1))
np.sort(arr1)[:, ::-1]

[[ 10   3  40]
 [ 20   6 100]]
[[  3  10  40]
 [  6  20 100]]
[[ 10   3  40]
 [ 20   6 100]]
[[  3  10  40]
 [  6  20 100]]


array([[ 40,  10,   3],
       [100,  20,   6]])

**Filter**

In [79]:
arr  = np.array([10,30,20,40])
print(arr)
print(arr>20)
print(arr[arr>20])

print(arr%2==0)
print(arr[arr%2==0])

print(arr[arr%2==1])

print(arr/2==1)

[10 30 20 40]
[False  True False  True]
[30 40]
[ True  True  True  True]
[10 30 20 40]
[]
[False False False False]


In [80]:
#where
arr = np.array([10,20,30,40])
print(np.where(arr>20,'true','false'))

['false' 'false' 'true' 'true']


In [81]:
print(np.where(arr>20,arr*2,arr))

[10 20 60 80]
