<a href="https://colab.research.google.com/github/DEVENDRAKUMAWAT650/Python_in_AWS-ML/blob/main/Day10_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [2]:
import numpy as np

In [3]:
import time


In [7]:
start = time.time()
sum1 = 0
for i in range(100000):
  sum1+=i*2
end = time.time()
#for list
print('for list',sum1,end-start)

#for numpy
start = time.time()
sum2=0
arr = np.arange(100000)*2
sum2 = arr.sum()
end = time.time()
print('for numpy',sum2,end-start) # arry works on every element

for list 9999900000 0.01610565185546875
for numpy 9999900000 0.001968860626220703


In [9]:
arr = np.zeros(5)
print(arr)

arr1 = np.zeros((2,3))
print(arr1)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
arr = np.ones(5)
print(arr)

arr1 = np.ones((2,3))
print(arr1)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
arr1 = np.full((5),3)
print(arr1)
arr = np.full((3,4),5)
print(arr)

[3 3 3 3 3]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [15]:
arr1= np.zeros(5)+7
print(arr1)

[7. 7. 7. 7. 7.]


In [16]:
# shape
arr = np.zeros(5)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

[0. 0. 0. 0. 0.]
(5,)
5
1
float64


In [17]:
# shape
arr = np.ones(5)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

[1. 1. 1. 1. 1.]
(5,)
5
1
float64


In [18]:
# shape
arr = np.full((5),5)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

[5 5 5 5 5]
(5,)
5
1
int64


In [20]:
#2D
# shape
arr = np.zeros((5,6))
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
(5, 6)
30
2
float64


In [21]:
# shape
arr = np.ones((5,2))
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
(5, 2)
10
2
float64


In [22]:
# shape
arr = np.full((5,3),4)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

[[4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]]
(5, 3)
15
2
int64


In [30]:
#Rshape
#1d arry
import numpy as np
arr = np.arange(6)
print(arr)

#2D
arr = arr.reshape(2,3)
print(arr)


arr1 = np.arange(15).reshape(5,3)
print(arr1)

#3D
arr2 = np.arange(24).reshape(2,3,4)
print(arr2)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [39]:
#flatten  || make a copy in memory
arrnew = arr.flatten()
arr = np.arange(6).reshape(2,3)
print(arr)
arr = arr.flatten()
print(arr)
arrnew = arr.flatten()
arrnew[0]=100
print(arr)

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [40]:
#ravel || original me change
arr = np.arange(6).reshape(2,3)
print(arr)
arr = arr.ravel()
print(arr)
arrnew = arr.ravel()
print(arrnew)
arrnew[0]=100
print(arr)

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
[100   1   2   3   4   5]


In [44]:
#transpose
arr = np.arange(6).reshape(2,3)
print(arr)
arr = arr.transpose()
print(arr)
arr1 = arr.T
print(arr1)


[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
[[0 1 2]
 [3 4 5]]
