<a href="https://colab.research.google.com/github/DEVENDRAKUMAWAT650/Python_in_AWS-ML/blob/main/Day9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**File** **Handling**

1.   r -> Read
2.   w -> write
3.   a -> append


In [2]:
file = open('Hello.txt','r')


FileNotFoundError: [Errno 2] No such file or directory: 'Hello.txt'

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/Colab Notebooks/Hello.txt'

In [4]:
from google.colab import drive
drive.mount('/content/drive')
data = open('/content/drive/My Drive/Colab Notebooks/Hello.txt','r')
print(data.read)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/Colab Notebooks/Hello.txt'

In [5]:
from google.colab import drive
drive.mount('/content/drive')

data = open('/content/drive/MyDrive/Colab Notebooks/Hello.txt', 'r')
print(data.read())
data.close()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Colab Notebooks/Hello.txt'

In [6]:
import os
print(os.path.exists('/content/drive/MyDrive/Colab Notebooks/Hello.txt'))

False


In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [8]:
!ls "/content/drive/MyDrive"

'bulid-partner responce.gsheet'
'Check this out on Flipkart'
'Colab Notebooks'
 Hello.txt
 IMG20240302191027.jpg.adding
 IMG20240302191058.jpg.adding
 IMG20240302191127.jpg.adding
 IMG20240903160114.jpg
 IMG20251031172633.jpg.adding
 IMG-20251031-WA0048.jpg.adding
 IMG-20251031-WA0057.jpg.adding
 IMG-20251031-WA0062.jpg.adding
 IMG-20251031-WA0064.jpg.adding
 IMG-20251031-WA0075.jpg.adding
 IMG-20251031-WA0076.jpg.adding
 IMG-20251031-WA0082.jpg.adding
 IMG-20251031-WA0086.jpg.adding
 IMG-20251031-WA0087.jpg.adding
 IMG-20251031-WA0094.jpg.adding
 IMG-20251031-WA0102.jpg.adding
 IMG-20251031-WA0104.jpg.adding
 IMG-20251031-WA0107.jpg.adding
 IMG-20251031-WA0111.jpg.adding
 IMG-20251031-WA0123.jpg.adding
 IMG-20251031-WA0126.jpg.adding
 IMG-20251031-WA0130.jpg.adding
 IMG-20251031-WA0131.jpg.adding
 IMG-20251031-WA0144.jpg.adding
 IMG-20251031-WA0147.jpg.adding
 IMG-20251031-WA0151.jpg
 IMG-20251031-WA0152.jpg.adding
 IMG-20251031-WA0159.jpg.adding
 IMG-20251031-WA0160.jpg.adding
 IMG-2

In [9]:
data = open('/content/drive/MyDrive/Hello.txt', 'r')
print(data.read())
data.close()

Testing file Handling


In [10]:
data = open('file1.csv','r')
data.read()

'name,roll no\ndheeraj,123\nkunal,1234\nabhishek,12345\npraveen,12356\nanjali,1234567'

In [12]:
data = open('/content/drive/MyDrive/file1.csv','r')
data.read()

'name,roll no\ndheeraj,123\nkunal,1234\nabhishek,12345\npraveen,12356\nanjali,1234567'

In [17]:
data1 = open('Hello.txt','w')
data1.write("We are indian")

13

In [22]:
data = open('/content/drive/MyDrive/Hello.txt', 'w')
print(data.write("We are indian"))
data.close()

13


In [23]:
data = open('/content/drive/MyDrive/Hello.txt', 'r')
print(data.read())
data.close()

We are indian


In [28]:
data = open('/content/drive/MyDrive/Hello.txt', 'r')
print(data.read())


data = open('/content/drive/MyDrive/Hello.txt', 'a')
print(data.write(' I am Devendra Kumawat'))
data.close()

data = open('/content/drive/MyDrive/Hello.txt', 'r')
print(data.read())

We are indian Iam Devendra Kumawat Iam Devendra Kumawat
22
We are indian Iam Devendra Kumawat Iam Devendra Kumawat I am Devendra Kumawat


In [32]:
data = open('file1.csv','r')
data.read()

#data = open('file1.csv','w')
#data.write("We are Indians")

data = open('file1.csv','a')
data.write("I am Devendra Kumawat")

data = open('file1.csv','r')
data.read()

'We are IndiansI am Devendra KumawatI am Devendra KumawatI am Devendra Kumawat'

#**NumPy**

In [33]:
import numpy as np

In [34]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [36]:
#Array Operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]


In [52]:
#2D Array (Matrix)
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix)
print(matrix.shape)
print(matrix[0][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [39]:
#3D Array
import numpy as np

arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [38]:
#Useful function
import numpy as np

arr = np.array([10, 20, 30, 40])

print(np.mean(arr))   # Average
print(np.sum(arr))    # Sum
print(np.max(arr))    # Maximum
print(np.min(arr))    # Minimum

25.0
100
40
10


In [44]:
import numpy as np
l = [10,20,30,40]
l*2
print('l =',l)

arr = np.array([10,20,30,40])
arr*2
print('arr =',arr)

l = [10, 20, 30, 40]
arr = [10 20 30 40]


In [45]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))
print(arr.shape)
print(arr[0])
print(arr[-1])


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1
5


In [48]:
#arang in numpy
import numpy as np
arr = np.arange(1,10,2)
print(arr)


[1 3 5 7 9]


In [51]:
for i in np.arange(0,21,2):
  print(i)

0
2
4
6
8
10
12
14
16
18
20
